# Form implementation generated from reading ui file '.\GUI\Accept.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Accept_Dialog(object):
    def setupUi(self, Accept_Dialog):
        Accept_Dialog.setObjectName("Accept_Dialog")
        Accept_Dialog.resize(218, 185)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\GUI\\Images/binance.png"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Accept_Dialog.setWindowIcon(icon)
        Accept_Dialog.setStyleSheet("background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
                                    "                                    stop: 0 #4c4c4c, stop: 1 #1f1f1f);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Accept_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_label = QtWidgets.QLabel(parent=Accept_Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.Main_label.setFont(font)
        self.Main_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                      "color: rgb(255, 255, 255);")
        self.Main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Main_label.setObjectName("Main_label")
        self.verticalLayout.addWidget(self.Main_label)
        self.check_buttonBox = QtWidgets.QDialogButtonBox(parent=Accept_Dialog)
        self.check_buttonBox.setStyleSheet("QDialogButtonBox QPushButton {\n"
                                           "    font: 700 12pt \"Microsoft JhengHei UI\";\n"
                                           "    background-color: #CCCCCC;\n"
                                           "    color: #333333;\n"
                                           "}\n"
                                           "\n"
                                           "QDialogButtonBox QPushButton:hover {\n"
                                           "    background-color: #D6D6D6;\n"
                                           "}")
        self.check_buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.check_buttonBox.setObjectName("check_buttonBox")
        self.verticalLayout.addWidget(
            self.check_buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Accept_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Accept_Dialog)

    def retranslateUi(self, Accept_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Accept_Dialog.setWindowTitle(_translate("Accept_Dialog", "確認視窗"))
        self.Main_label.setText(_translate("Accept_Dialog", "文字插入區域"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Accept_Dialog = QtWidgets.QDialog()
    ui = Ui_Accept_Dialog()
    ui.setupUi(Accept_Dialog)
    Accept_Dialog.show()
    sys.exit(app.exec())
