# Form implementation generated from reading ui file '.\GUI\DeadLine.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_DeadLine(object):
    def setupUi(self, Dialog_DeadLine):
        Dialog_DeadLine.setObjectName("Dialog_DeadLine")
        Dialog_DeadLine.resize(302, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\GUI\\Images/binance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog_DeadLine.setWindowIcon(icon)
        Dialog_DeadLine.setStyleSheet("background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                    stop: 0 #4c4c4c, stop: 1 #1f1f1f);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_DeadLine)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=Dialog_DeadLine)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 92, 70);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_2_date = QtWidgets.QLabel(parent=Dialog_DeadLine)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2_date.setFont(font)
        self.label_2_date.setStyleSheet("color: rgb(255, 129, 97);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_2_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2_date.setObjectName("label_2_date")
        self.verticalLayout.addWidget(self.label_2_date)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(parent=Dialog_DeadLine)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_accept.setFont(font)
        self.pushButton_accept.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(167, 167, 167);")
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_DeadLine)
        QtCore.QMetaObject.connectSlotsByName(Dialog_DeadLine)

    def retranslateUi(self, Dialog_DeadLine):
        _translate = QtCore.QCoreApplication.translate
        Dialog_DeadLine.setWindowTitle(_translate("Dialog_DeadLine", "Dialog"))
        self.label_title.setText(_translate("Dialog_DeadLine", "警告!你的交易期限已經到期"))
        self.label_2_date.setText(_translate("Dialog_DeadLine", "到期日:2023-05-04"))
        self.pushButton_accept.setText(_translate("Dialog_DeadLine", "確認"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_DeadLine = QtWidgets.QDialog()
    ui = Ui_Dialog_DeadLine()
    ui.setupUi(Dialog_DeadLine)
    Dialog_DeadLine.show()
    sys.exit(app.exec())
