# Form implementation generated from reading ui file '.\GUI\Error_Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Error(object):
    def setupUi(self, Dialog_Error):
        Dialog_Error.setObjectName("Dialog_Error")
        Dialog_Error.resize(237, 231)
        Dialog_Error.setMaximumSize(QtCore.QSize(429, 606))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Error)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog_Error)
        self.label_2.setMaximumSize(QtCore.QSize(220, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\GUI\Images\Attention.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Dialog_Error)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_Error = QtWidgets.QPushButton(Dialog_Error)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton_Error.setFont(font)
        self.pushButton_Error.setStyleSheet("QPushButton {\n"
                                            "    background-color: rgb(127, 127, 125);\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: rgb(170, 170, 170);\n"
                                            "}")
        self.pushButton_Error.setObjectName("pushButton_Error")
        self.verticalLayout.addWidget(self.pushButton_Error)

        self.retranslateUi(Dialog_Error)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Error)

    def retranslateUi(self, Dialog_Error):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Error.setWindowTitle(_translate("Dialog_Error", "Error"))
        self.label.setText(_translate("Dialog_Error", "資訊不足請重新確認"))
        self.pushButton_Error.setText(_translate("Dialog_Error", "確認"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Error = QtWidgets.QDialog()
    ui = Ui_Dialog_Error()
    ui.setupUi(Dialog_Error)
    Dialog_Error.show()
    sys.exit(app.exec())
