# Form implementation generated from reading ui file '.\GUI\Phone_error.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Phone_error(object):
    def setupUi(self, Dialog_Phone_error):
        Dialog_Phone_error.setObjectName("Dialog_Phone_error")
        Dialog_Phone_error.resize(266, 213)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\GUI\\Images/binance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog_Phone_error.setWindowIcon(icon)
        Dialog_Phone_error.setStyleSheet("background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                    stop: 0 #4c4c4c, stop: 1 #1f1f1f);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_Phone_error)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=Dialog_Phone_error)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 92, 70);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_content = QtWidgets.QLabel(parent=Dialog_Phone_error)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_content.setFont(font)
        self.label_content.setStyleSheet("color: rgb(255, 92, 70);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_content.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_content.setObjectName("label_content")
        self.verticalLayout.addWidget(self.label_content)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton_accept = QtWidgets.QPushButton(parent=Dialog_Phone_error)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.pushButton_accept.setFont(font)
        self.pushButton_accept.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(167, 167, 167);")
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.verticalLayout_2.addWidget(self.pushButton_accept)

        self.retranslateUi(Dialog_Phone_error)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Phone_error)

    def retranslateUi(self, Dialog_Phone_error):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Phone_error.setWindowTitle(_translate("Dialog_Phone_error", "Dialog"))
        self.label_title.setText(_translate("Dialog_Phone_error", "警告!輸入手機號碼錯誤!"))
        self.label_content.setText(_translate("Dialog_Phone_error", "請重新輸入!"))
        self.pushButton_accept.setText(_translate("Dialog_Phone_error", "確認"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Phone_error = QtWidgets.QDialog()
    ui = Ui_Dialog_Phone_error()
    ui.setupUi(Dialog_Phone_error)
    Dialog_Phone_error.show()
    sys.exit(app.exec())
