# Form implementation generated from reading ui file '.\GUI\Reload.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reload_Dialog(object):
    def setupUi(self, Reload_Dialog):
        Reload_Dialog.setObjectName("Reload_Dialog")
        Reload_Dialog.resize(194, 138)
        Reload_Dialog.setStyleSheet("background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
                                    "                                    stop: 0 #4c4c4c, stop: 1 #1f1f1f);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Reload_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_label = QtWidgets.QLabel(parent=Reload_Dialog)
        self.Main_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 700 12pt \"Microsoft JhengHei UI\";\n"
                                      "background-color: rgba(255, 255, 255, 0);")
        self.Main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Main_label.setObjectName("Main_label")
        self.verticalLayout.addWidget(self.Main_label)
        self.Main_progressBar = QtWidgets.QProgressBar(parent=Reload_Dialog)
        self.Main_progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.Main_progressBar.setProperty("value", 24)
        self.Main_progressBar.setObjectName("Main_progressBar")
        self.verticalLayout.addWidget(self.Main_progressBar)

        self.retranslateUi(Reload_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Reload_Dialog)

    def retranslateUi(self, Reload_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Reload_Dialog.setWindowTitle(_translate("Reload_Dialog", "Dialog"))
        self.Main_label.setText(_translate("Reload_Dialog", "資料回補中..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reload_Dialog = QtWidgets.QDialog()
    ui = Ui_Reload_Dialog()
    ui.setupUi(Reload_Dialog)
    Reload_Dialog.show()
    sys.exit(app.exec())
